###
POST localhost:8080/rakuten/transaction/analysis
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file1.csv"
Content-Type: text/csv

< ./samplefiles/credit.csv
--boundary
Content-Disposition: form-data; name="file"; filename="file2.csv"
Content-Type: text/csv

< ./samplefiles/debit.csv
--boundary--



###
# curl -X POST --location "http://localhost:8080/rakuten/transaction/analysis"
#    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/credit.csv;filename=file1.csv;type=text/csv"
#    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/debit.csv;filename=file2.csv;type=text/csv"
POST http://localhost:8080/rakuten/transaction/analysis
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file1.csv"

< ./samplefiles/RB-debitmeisai.csv; type=text/csv
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file2.csv"

< ./samplefiles/enavi202504(4070).csv; type=text/csv
--WebAppBoundary--

###


# curl -X POST --location "http://localhost:8080/rakuten/transaction/analysis"
#    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/credit.csv;filename=file1.csv;type=text/csv"
#    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/debit.csv;filename=file2.csv;type=text/csv"
POST http://localhost:8080/rakuten/transaction/analysis
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file1.csv"

< ./samplefiles/credit.csv ;type=text/csv
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file2.sv"

< /Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/debit.csv;type=text/csv
--WebAppBoundary--

###


 curl -X POST --location "http://localhost:8080/rakuten/transaction/analysis"
    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/credit.csv;filename=file1.csv;type=text/csv"
    -F "file=@/Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/debit.csv;filename=file2.csv;type=text/csv"
POST http://localhost:8080/rakuten/transaction/analysis
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="csv"

< /Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/file1.csv;type=text/csv
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="csv"

< /Users/bandousatoshi/dev/golang/rakuten-transaction-analytics/httpclient/samplefiles/file2.csv;type=text/csv
--WebAppBoundary--

###






