// Code generated by MockGen. DO NOT EDIT.
// Source: calculate_score_rule.go
//
// Generated by this command:
//
//	mockgen -source=calculate_score_rule.go -destination=../../../internal/mocks/domain/rule/calculate_score_rule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	aggregate "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/domain/aggregate"
	gomock "go.uber.org/mock/gomock"
)

// MockICalculateScoreRule is a mock of ICalculateScoreRule interface.
type MockICalculateScoreRule struct {
	ctrl     *gomock.Controller
	recorder *MockICalculateScoreRuleMockRecorder
	isgomock struct{}
}

// MockICalculateScoreRuleMockRecorder is the mock recorder for MockICalculateScoreRule.
type MockICalculateScoreRuleMockRecorder struct {
	mock *MockICalculateScoreRule
}

// NewMockICalculateScoreRule creates a new mock instance.
func NewMockICalculateScoreRule(ctrl *gomock.Controller) *MockICalculateScoreRule {
	mock := &MockICalculateScoreRule{ctrl: ctrl}
	mock.recorder = &MockICalculateScoreRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICalculateScoreRule) EXPECT() *MockICalculateScoreRuleMockRecorder {
	return m.recorder
}

// CalculateScore mocks base method.
func (m *MockICalculateScoreRule) CalculateScore(ctx context.Context, transactionReportDto *aggregate.TransactionReportDto) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateScore", ctx, transactionReportDto)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateScore indicates an expected call of CalculateScore.
func (mr *MockICalculateScoreRuleMockRecorder) CalculateScore(ctx, transactionReportDto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateScore", reflect.TypeOf((*MockICalculateScoreRule)(nil).CalculateScore), ctx, transactionReportDto)
}
