// Code generated by MockGen. DO NOT EDIT.
// Source: categorize_rule.go
//
// Generated by this command:
//
//	mockgen -source=categorize_rule.go -destination=../../../internal/mocks/domain/rule/categorize_rule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICategorizeRule is a mock of ICategorizeRule interface.
type MockICategorizeRule struct {
	ctrl     *gomock.Controller
	recorder *MockICategorizeRuleMockRecorder
	isgomock struct{}
}

// MockICategorizeRuleMockRecorder is the mock recorder for MockICategorizeRule.
type MockICategorizeRuleMockRecorder struct {
	mock *MockICategorizeRule
}

// NewMockICategorizeRule creates a new mock instance.
func NewMockICategorizeRule(ctrl *gomock.Controller) *MockICategorizeRule {
	mock := &MockICategorizeRule{ctrl: ctrl}
	mock.recorder = &MockICategorizeRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICategorizeRule) EXPECT() *MockICategorizeRuleMockRecorder {
	return m.recorder
}

// IsContainFixedCosts mocks base method.
func (m *MockICategorizeRule) IsContainFixedCosts(val string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsContainFixedCosts", val)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsContainFixedCosts indicates an expected call of IsContainFixedCosts.
func (mr *MockICategorizeRuleMockRecorder) IsContainFixedCosts(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsContainFixedCosts", reflect.TypeOf((*MockICategorizeRule)(nil).IsContainFixedCosts), val)
}

// IsFoodCosts mocks base method.
func (m *MockICategorizeRule) IsFoodCosts(val string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFoodCosts", val)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFoodCosts indicates an expected call of IsFoodCosts.
func (mr *MockICategorizeRuleMockRecorder) IsFoodCosts(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFoodCosts", reflect.TypeOf((*MockICategorizeRule)(nil).IsFoodCosts), val)
}

// IsOtherCosts mocks base method.
func (m *MockICategorizeRule) IsOtherCosts(val string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOtherCosts", val)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOtherCosts indicates an expected call of IsOtherCosts.
func (mr *MockICategorizeRuleMockRecorder) IsOtherCosts(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOtherCosts", reflect.TypeOf((*MockICategorizeRule)(nil).IsOtherCosts), val)
}

// IsVariableCosts mocks base method.
func (m *MockICategorizeRule) IsVariableCosts(val string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsVariableCosts", val)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsVariableCosts indicates an expected call of IsVariableCosts.
func (mr *MockICategorizeRuleMockRecorder) IsVariableCosts(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsVariableCosts", reflect.TypeOf((*MockICategorizeRule)(nil).IsVariableCosts), val)
}

// IsWasteCosts mocks base method.
func (m *MockICategorizeRule) IsWasteCosts(val string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWasteCosts", val)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWasteCosts indicates an expected call of IsWasteCosts.
func (mr *MockICategorizeRuleMockRecorder) IsWasteCosts(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWasteCosts", reflect.TypeOf((*MockICategorizeRule)(nil).IsWasteCosts), val)
}
