// Code generated by MockGen. DO NOT EDIT.
// Source: file_reader_rule.go
//
// Generated by this command:
//
//	mockgen -source=file_reader_rule.go -destination=../../../internal/mocks/domain/rule/file_reader_rule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIFileReaderRule is a mock of IFileReaderRule interface.
type MockIFileReaderRule struct {
	ctrl     *gomock.Controller
	recorder *MockIFileReaderRuleMockRecorder
	isgomock struct{}
}

// MockIFileReaderRuleMockRecorder is the mock recorder for MockIFileReaderRule.
type MockIFileReaderRuleMockRecorder struct {
	mock *MockIFileReaderRule
}

// NewMockIFileReaderRule creates a new mock instance.
func NewMockIFileReaderRule(ctrl *gomock.Controller) *MockIFileReaderRule {
	mock := &MockIFileReaderRule{ctrl: ctrl}
	mock.recorder = &MockIFileReaderRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileReaderRule) EXPECT() *MockIFileReaderRuleMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockIFileReaderRule) ReadAll(file *multipart.FileHeader) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", file)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockIFileReaderRuleMockRecorder) ReadAll(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockIFileReaderRule)(nil).ReadAll), file)
}
