// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_rule.go
//
// Generated by this command:
//
//	mockgen -source=transaction_rule.go -destination=../../../internal/mocks/domain/rule/transaction_rule.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockITransactionRule is a mock of ITransactionRule interface.
type MockITransactionRule struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionRuleMockRecorder
	isgomock struct{}
}

// MockITransactionRuleMockRecorder is the mock recorder for MockITransactionRule.
type MockITransactionRuleMockRecorder struct {
	mock *MockITransactionRule
}

// NewMockITransactionRule creates a new mock instance.
func NewMockITransactionRule(ctrl *gomock.Controller) *MockITransactionRule {
	mock := &MockITransactionRule{ctrl: ctrl}
	mock.recorder = &MockITransactionRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionRule) EXPECT() *MockITransactionRuleMockRecorder {
	return m.recorder
}

// CalculateAmount mocks base method.
func (m *MockITransactionRule) CalculateAmount() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAmount")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateAmount indicates an expected call of CalculateAmount.
func (mr *MockITransactionRuleMockRecorder) CalculateAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAmount", reflect.TypeOf((*MockITransactionRule)(nil).CalculateAmount))
}

// CalculateFixedCosts mocks base method.
func (m *MockITransactionRule) CalculateFixedCosts() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFixedCosts")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateFixedCosts indicates an expected call of CalculateFixedCosts.
func (mr *MockITransactionRuleMockRecorder) CalculateFixedCosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFixedCosts", reflect.TypeOf((*MockITransactionRule)(nil).CalculateFixedCosts))
}

// CalculateFoodExpenses mocks base method.
func (m *MockITransactionRule) CalculateFoodExpenses() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFoodExpenses")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateFoodExpenses indicates an expected call of CalculateFoodExpenses.
func (mr *MockITransactionRuleMockRecorder) CalculateFoodExpenses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFoodExpenses", reflect.TypeOf((*MockITransactionRule)(nil).CalculateFoodExpenses))
}

// CalculateOtherExpenses mocks base method.
func (m *MockITransactionRule) CalculateOtherExpenses() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateOtherExpenses")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateOtherExpenses indicates an expected call of CalculateOtherExpenses.
func (mr *MockITransactionRuleMockRecorder) CalculateOtherExpenses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateOtherExpenses", reflect.TypeOf((*MockITransactionRule)(nil).CalculateOtherExpenses))
}

// CalculateVariableCosts mocks base method.
func (m *MockITransactionRule) CalculateVariableCosts() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateVariableCosts")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateVariableCosts indicates an expected call of CalculateVariableCosts.
func (mr *MockITransactionRuleMockRecorder) CalculateVariableCosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateVariableCosts", reflect.TypeOf((*MockITransactionRule)(nil).CalculateVariableCosts))
}

// CalculateWasteExpenses mocks base method.
func (m *MockITransactionRule) CalculateWasteExpenses() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateWasteExpenses")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CalculateWasteExpenses indicates an expected call of CalculateWasteExpenses.
func (mr *MockITransactionRuleMockRecorder) CalculateWasteExpenses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateWasteExpenses", reflect.TypeOf((*MockITransactionRule)(nil).CalculateWasteExpenses))
}

// Categorize mocks base method.
func (m *MockITransactionRule) Categorize() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Categorize")
}

// Categorize indicates an expected call of Categorize.
func (mr *MockITransactionRuleMockRecorder) Categorize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Categorize", reflect.TypeOf((*MockITransactionRule)(nil).Categorize))
}

// GetTransactions mocks base method.
func (m *MockITransactionRule) GetTransactions() []*models.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions")
	ret0, _ := ret[0].([]*models.Transaction)
	return ret0
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockITransactionRuleMockRecorder) GetTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockITransactionRule)(nil).GetTransactions))
}
