// Code generated by MockGen. DO NOT EDIT.
// Source: analytics_transaction_usecase.go
//
// Generated by this command:
//
//	mockgen -source=analytics_transaction_usecase.go -destination=../../internal/mocks/infrastructure/analytics_transaction_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/handler/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnalyticsTransactionUsecase is a mock of IAnalyticsTransactionUsecase interface.
type MockIAnalyticsTransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIAnalyticsTransactionUsecaseMockRecorder
	isgomock struct{}
}

// MockIAnalyticsTransactionUsecaseMockRecorder is the mock recorder for MockIAnalyticsTransactionUsecase.
type MockIAnalyticsTransactionUsecaseMockRecorder struct {
	mock *MockIAnalyticsTransactionUsecase
}

// NewMockIAnalyticsTransactionUsecase creates a new mock instance.
func NewMockIAnalyticsTransactionUsecase(ctrl *gomock.Controller) *MockIAnalyticsTransactionUsecase {
	mock := &MockIAnalyticsTransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockIAnalyticsTransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnalyticsTransactionUsecase) EXPECT() *MockIAnalyticsTransactionUsecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIAnalyticsTransactionUsecase) Run(arg0 context.Context, arg1 dto.TransactionRequest) (*dto.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(*dto.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIAnalyticsTransactionUsecaseMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIAnalyticsTransactionUsecase)(nil).Run), arg0, arg1)
}
