// Code generated by MockGen. DO NOT EDIT.
// Source: analytics_transaction_usecase.go
//
// Generated by this command:
//
//	mockgen -source=analytics_transaction_usecase.go -destination=../../internal/mocks/infrastructure/analytics_transaction_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/handler/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIAnalyticsTransactionUsecase is a mock of IAnalyticsTransactionUsecase interface.
type MockIAnalyticsTransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIAnalyticsTransactionUsecaseMockRecorder
	isgomock struct{}
}

// MockIAnalyticsTransactionUsecaseMockRecorder is the mock recorder for MockIAnalyticsTransactionUsecase.
type MockIAnalyticsTransactionUsecaseMockRecorder struct {
	mock *MockIAnalyticsTransactionUsecase
}

// NewMockIAnalyticsTransactionUsecase creates a new mock instance.
func NewMockIAnalyticsTransactionUsecase(ctrl *gomock.Controller) *MockIAnalyticsTransactionUsecase {
	mock := &MockIAnalyticsTransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockIAnalyticsTransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnalyticsTransactionUsecase) EXPECT() *MockIAnalyticsTransactionUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIAnalyticsTransactionUsecase) Execute(ctx context.Context, req dto.TransactionRequest) (*dto.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*dto.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIAnalyticsTransactionUsecaseMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIAnalyticsTransactionUsecase)(nil).Execute), ctx, req)
}

// Run mocks base method.
func (m *MockIAnalyticsTransactionUsecase) Run(ctx context.Context, req dto.TransactionRequest, files []*multipart.FileHeader) (*dto.TransactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, req, files)
	ret0, _ := ret[0].(*dto.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIAnalyticsTransactionUsecaseMockRecorder) Run(ctx, req, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIAnalyticsTransactionUsecase)(nil).Run), ctx, req, files)
}
