// Code generated by MockGen. DO NOT EDIT.
// Source: retrieve_transaction_usecase.go
//
// Generated by this command:
//
//	mockgen -source=retrieve_transaction_usecase.go -destination=../../internal/mocks/infrastructure/retrieve_transaction_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/handler/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockIRetrieveTransactionUsecase is a mock of IRetrieveTransactionUsecase interface.
type MockIRetrieveTransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockIRetrieveTransactionUsecaseMockRecorder
	isgomock struct{}
}

// MockIRetrieveTransactionUsecaseMockRecorder is the mock recorder for MockIRetrieveTransactionUsecase.
type MockIRetrieveTransactionUsecaseMockRecorder struct {
	mock *MockIRetrieveTransactionUsecase
}

// NewMockIRetrieveTransactionUsecase creates a new mock instance.
func NewMockIRetrieveTransactionUsecase(ctrl *gomock.Controller) *MockIRetrieveTransactionUsecase {
	mock := &MockIRetrieveTransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockIRetrieveTransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRetrieveTransactionUsecase) EXPECT() *MockIRetrieveTransactionUsecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIRetrieveTransactionUsecase) Run(ctx context.Context, files []*multipart.FileHeader) (*dto.RetrieveTransactionResponses, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, files)
	ret0, _ := ret[0].(*dto.RetrieveTransactionResponses)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIRetrieveTransactionUsecaseMockRecorder) Run(ctx, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIRetrieveTransactionUsecase)(nil).Run), ctx, files)
}
