// Code generated by MockGen. DO NOT EDIT.
// Source: ratio_rule_repository.go
//
// Generated by this command:
//
//	mockgen -source=ratio_rule_repository.go -destination=../../../internal/mocks/domain/repository/ratio_rule_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRatioRuleRepository is a mock of RatioRuleRepository interface.
type MockRatioRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatioRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockRatioRuleRepositoryMockRecorder is the mock recorder for MockRatioRuleRepository.
type MockRatioRuleRepositoryMockRecorder struct {
	mock *MockRatioRuleRepository
}

// NewMockRatioRuleRepository creates a new mock instance.
func NewMockRatioRuleRepository(ctrl *gomock.Controller) *MockRatioRuleRepository {
	mock := &MockRatioRuleRepository{ctrl: ctrl}
	mock.recorder = &MockRatioRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatioRuleRepository) EXPECT() *MockRatioRuleRepositoryMockRecorder {
	return m.recorder
}

// SelectAll mocks base method.
func (m *MockRatioRuleRepository) SelectAll(ctx context.Context) ([]*models.RatioRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll", ctx)
	ret0, _ := ret[0].([]*models.RatioRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockRatioRuleRepositoryMockRecorder) SelectAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockRatioRuleRepository)(nil).SelectAll), ctx)
}
