// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_report_repository.go
//
// Generated by this command:
//
//	mockgen -source=transaction_report_repository.go -destination=../../../internal/mocks/domain/repository/transaction_report_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/satoshisyohu/rakuten-transaction-analytics/pkg/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionReportRepository is a mock of TransactionReportRepository interface.
type MockTransactionReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionReportRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionReportRepositoryMockRecorder is the mock recorder for MockTransactionReportRepository.
type MockTransactionReportRepositoryMockRecorder struct {
	mock *MockTransactionReportRepository
}

// NewMockTransactionReportRepository creates a new mock instance.
func NewMockTransactionReportRepository(ctrl *gomock.Controller) *MockTransactionReportRepository {
	mock := &MockTransactionReportRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionReportRepository) EXPECT() *MockTransactionReportRepositoryMockRecorder {
	return m.recorder
}

// SaveAll mocks base method.
func (m *MockTransactionReportRepository) SaveAll(ctx context.Context, arg1 []*models.TransactionReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockTransactionReportRepositoryMockRecorder) SaveAll(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockTransactionReportRepository)(nil).SaveAll), ctx, arg1)
}

// SelectByYearMonth mocks base method.
func (m *MockTransactionReportRepository) SelectByYearMonth(ctx context.Context, yearMonth string) ([]*models.TransactionReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectByYearMonth", ctx, yearMonth)
	ret0, _ := ret[0].([]*models.TransactionReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectByYearMonth indicates an expected call of SelectByYearMonth.
func (mr *MockTransactionReportRepositoryMockRecorder) SelectByYearMonth(ctx, yearMonth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectByYearMonth", reflect.TypeOf((*MockTransactionReportRepository)(nil).SelectByYearMonth), ctx, yearMonth)
}
